#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jul 19 19:44:39 IST 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_fifo_behav -key {Behavioral:sim_1:Functional:tb_fifo} -tclbatch tb_fifo.tcl -view /home/chetan/vivado_workspace/Async_fifo/fifo_tb_behav.wcfg -view /home/chetan/vivado_workspace/Async_fifo/tb_fifo_behav.wcfg -log simulate.log"
xsim tb_fifo_behav -key {Behavioral:sim_1:Functional:tb_fifo} -tclbatch tb_fifo.tcl -view /home/chetan/vivado_workspace/Async_fifo/fifo_tb_behav.wcfg -view /home/chetan/vivado_workspace/Async_fifo/tb_fifo_behav.wcfg -log simulate.log

